---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: replicated
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 1
  dataPool:
    failureDomain: osd
    replicated:
      size: 1
  gateway:
    type: s3
    sslCertificateRef:
    port: 80
    securePort:
    instances: 1
    allNodes: false
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: replicated
  namespace: rook-ceph
spec:
  store: replicated
  displayName: "Replicated"
